"""Bounded, non-executable analog graph and synchronized playback contracts."""

import math
from typing import Annotated, Literal, Self

from pydantic import BaseModel, ConfigDict, Field, model_validator

Finite = Annotated[float, Field(strict=True, allow_inf_nan=False)]
Identifier = Annotated[str, Field(pattern=r"^[a-zA-Z][a-zA-Z0-9_]{0,15}$")]


class StrictModel(BaseModel):
    """Reject unknown fields at every graph boundary."""

    model_config = ConfigDict(extra="forbid")


class PulseSettings(StrictModel):
    """A bounded square-wave source; edge times are generated by the compiler."""

    period: Finite = Field(ge=1e-6, le=10)
    width: Finite = Field(gt=0, le=10)
    delay: Finite = Field(ge=0, le=10)

    @model_validator(mode="after")
    def validate_width(self) -> Self:
        """Leave nonzero time for both pulse states."""
        if not 0.01 * self.period <= self.width <= 0.99 * self.period:
            raise ValueError("Pulse width must be 1–99% of its period")
        return self


class Part(StrictModel):
    """One ideal analog component, with visual placement independent of wiring."""

    id: Identifier
    kind: Literal["R", "C", "L", "V", "PULSE", "GND"]
    value: Finite
    x: int = Field(strict=True, ge=2, le=38)
    y: int = Field(strict=True, ge=2, le=22)
    rotation: Literal[0, 90, 180, 270] = 0
    pulse: PulseSettings | None = None

    @model_validator(mode="after")
    def validate_value(self) -> Self:
        """Bound physical values without permitting expressions or SPICE text."""
        limits = {"R": (1, 1e8), "C": (1e-12, 1), "L": (1e-9, 100),
                  "V": (-100, 100), "PULSE": (-100, 100), "GND": (0, 0)}
        minimum, maximum = limits[self.kind]
        if not minimum <= self.value <= maximum:
            raise ValueError(f"{self.kind} value must be between {minimum:g} and {maximum:g}")
        if (self.kind == "PULSE") != (self.pulse is not None):
            raise ValueError("Pulse settings are required only for pulse sources")
        return self


class Pin(StrictModel):
    """A stable terminal reference, unaffected by moving or rotating a part."""

    part: Identifier
    terminal: Literal[0, 1]


class Wire(StrictModel):
    """An explicit connection; drawn crossings are never implicit junctions."""

    a: Pin
    b: Pin


class Timing(StrictModel):
    """Solver maximum step and uniform output interval, distinct from playback."""

    stop: Finite = Field(gt=0, le=10)
    step: Finite = Field(ge=1e-7, le=1)

    @model_validator(mode="after")
    def validate_sample_budget(self) -> Self:
        """Bound both computation and synchronized response size."""
        if not 10 <= self.stop / self.step <= 2000:
            raise ValueError("Choose 10–2000 time intervals (duration divided by sample interval)")
        return self


class SchematicRequest(StrictModel):
    """A small analog graph, never an executable netlist."""

    parts: list[Part] = Field(min_length=2, max_length=20)
    wires: list[Wire] = Field(min_length=1, max_length=40)
    timing: Timing

    @model_validator(mode="after")
    def validate_pulse_budget(self) -> Self:
        """Prevent excessive switching events within the simulation window."""
        for part in self.parts:
            if part.pulse and self.timing.stop / part.pulse.period > 1000:
                raise ValueError("At most 1000 pulse periods may be simulated")
        return self


class Trace(StrictModel):
    """A finite signal on the report's one shared time axis."""

    name: str
    unit: Literal["V", "A"]
    values: list[Finite] = Field(min_length=11, max_length=2002)


class SchematicResponse(StrictModel):
    """Every trace has one value per uniformly sampled frame."""

    correlation_id: str
    status: Literal["completed"] = "completed"
    times: list[Finite] = Field(min_length=11, max_length=2002)
    traces: list[Trace] = Field(min_length=1, max_length=60)
    pin_nodes: dict[str, str]
    netlist: str
    warnings: list[str]

    @model_validator(mode="after")
    def validate_frames(self) -> Self:
        """Reject mismatched, non-increasing or non-finite worker frames."""
        if any(b <= a for a, b in zip(self.times, self.times[1:], strict=False)):
            raise ValueError("Frame times must increase")
        interval = self.times[1] - self.times[0]
        if any(not math.isclose(b - a, interval, rel_tol=1e-6, abs_tol=1e-14)
               for a, b in zip(self.times, self.times[1:], strict=False)):
            raise ValueError("Frame times must be uniform")
        if any(len(trace.values) != len(self.times) for trace in self.traces):
            raise ValueError("All signals must share the same time axis")
        if len({trace.name for trace in self.traces}) != len(self.traces):
            raise ValueError("Signal names must be unique")
        if not math.isclose(self.times[0], 0, abs_tol=1e-12):
            raise ValueError("Playback must start at zero")
        return self


class SchematicJob(StrictModel):
    """Allow-listed IPC operation for a structured analog graph."""

    operation: Literal["schematic"]
    request: SchematicRequest
    correlation_id: str = Field(min_length=1, max_length=64, pattern=r"^[a-zA-Z0-9_-]+$")
