from collections.abc import Mapping
from typing import AsyncContextManager

class PostgresError(Exception): ...
class Connection:
    async def execute(self, query: str, *arguments: object) -> str: ...
    async def fetch(self, query: str, *arguments: object) -> list[Mapping[str, object]]: ...
    async def fetchval(self, query: str, *arguments: object) -> object: ...
    async def fetchrow(self, query: str, *arguments: object) -> Mapping[str, object] | None: ...
    def transaction(self) -> AsyncContextManager[None]: ...
class Pool:
    def acquire(self) -> AsyncContextManager[Connection]: ...
    async def close(self) -> None: ...
async def create_pool(dsn: str, *, min_size: int = ..., max_size: int = ...,
                      command_timeout: float = ...) -> Pool: ...
