import { expect, test } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

test('real sine playback reverses on-grid current, synchronizes scopes, pins probes without wiring and qualifies phase', async ({ page }) => {
  let jobs = 0;
  page.on('request', request => { if (request.url().endsWith('/api/schematic/simulate')) jobs++; });
  await page.goto('/?mode=build');
  page.once('dialog', dialog => dialog.accept());
  await page.getByLabel('AC example', { exact: true }).selectOption('C');
  await page.getByRole('button', { name: 'Run analysis', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Synchronized scope' })).toBeVisible();
  await page.getByRole('button', { name: 'Observe', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Play', exact: true })).toBeVisible();
  await expect(page.locator('.observation-node-labels .node-reading')).toHaveCount(3);
  await page.getByLabel('Watch from (ms)').fill('675');
  await expect(page.getByLabel('Grid observation time')).toContainText('675 ms');
  await expect(page.locator('.branch-direction[data-direction="1 → 0"]')).toHaveCount(2);
  await page.getByRole('slider', { name: 'Seek voltage plot', exact: true }).press('ArrowRight');
  await expect(page.getByLabel('Grid observation time')).toContainText('676 ms');
  await page.setViewportSize({ width: 1280, height: 1400 });
  await page.getByRole('button', { name: 'Observe', exact: true }).focus();
  await page.keyboard.press('Control+Home');
  await page.locator('.grid-panel').screenshot({ path: '/tmp/circuit-lab-observation-grid.png' });
  await page.getByLabel('Probe tool').selectOption('differential');
  await page.getByRole('button', { name: 'R1 terminal 0', exact: true }).press('Enter');
  await page.getByRole('button', { name: 'R1 terminal 1', exact: true }).press('Enter');
  await expect(page.getByRole('button', { name: 'Remove probe ΔV:R1:0−R1:1', exact: true })).toBeVisible();
  await expect(page.locator('.schematic-wire')).toHaveCount(4);
  await page.getByRole('button', { name: 'Last three cycles', exact: true }).click();
  await expect(page.getByRole('row').filter({ hasText: 'ΔV:C1:0−C1:1' })).toContainText('-32.1°');
  await page.screenshot({ path: '/tmp/circuit-lab-observation-time.png', fullPage: true });
  expect(jobs).toBe(1);
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]);
  await page.setViewportSize({ width: 390, height: 844 });
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.getByLabel('Moving current markers', { exact: true }).check();
  await page.getByRole('button', { name: 'Play', exact: true }).click();
  await expect(page.locator('.flow-marker').first()).toBeHidden();
  await expect(page.locator('.branch-direction').first()).toBeVisible();
});

test('real frequency sweep shares grid/cursor/gain/phase, retains valid time results and invalidates only affected analysis', async ({ page }) => {
  let timeJobs = 0, frequencyJobs = 0;
  page.on('request', request => { if (request.url().endsWith('/api/schematic/simulate')) timeJobs++;
    if (request.url().endsWith('/api/schematic/ac')) frequencyJobs++; });
  await page.goto('/?mode=build');
  await page.getByRole('button', { name: 'Run analysis', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Synchronized scope' })).toBeVisible();
  await page.getByLabel('Analysis', { exact: true }).selectOption('ac');
  await page.getByRole('button', { name: 'Run analysis', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Frequency response', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Observe', exact: true }).click();
  await page.getByLabel('Frequency cursor', { exact: true }).fill('50');
  await expect(page.getByLabel('Grid observation frequency')).toContainText('10 Hz');
  await expect(page.getByRole('row', { name: /^C1 / })).toContainText('846.7 mV ∠ -32.1°');
  await page.screenshot({ path: '/tmp/circuit-lab-observation-frequency.png', fullPage: true });
  await expect(page.locator('.branch-direction')).toHaveCount(0);
  await expect(page.getByLabel('Moving current markers', { exact: true })).toBeDisabled();
  await page.getByLabel('Voltage display', { exact: true }).selectOption('db');
  await expect(page.getByRole('heading', { name: 'Voltage · dB' })).toBeVisible();
  await page.getByLabel('Unwrap plotted phase', { exact: true }).check();
  await expect(page.getByRole('heading', { name: 'Unwrapped phase · degrees' })).toBeVisible();
  await page.getByRole('slider', { name: 'Seek current plot', exact: true }).press('ArrowRight');
  await expect(page.getByLabel('Frequency cursor', { exact: true })).toHaveValue('51');
  const download = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export simulation', exact: true }).click();
  expect((await download).suggestedFilename()).toBe('circuit-lab-ac-report.json');
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]);
  await page.setViewportSize({ width: 390, height: 844 });
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.getByLabel('Analysis', { exact: true }).selectOption('transient');
  await expect(page.getByRole('heading', { name: 'Synchronized scope' })).toBeVisible();
  await page.getByRole('button', { name: 'Build', exact: true }).click();
  await page.getByLabel('Sample interval (ms)', { exact: true }).fill('.2');
  await expect(page.getByRole('heading', { name: 'Synchronized scope' })).toHaveCount(0);
  await page.getByLabel('Analysis', { exact: true }).selectOption('ac');
  await expect(page.getByRole('heading', { name: 'Frequency response', exact: true })).toBeVisible();
  await page.getByLabel('AC amplitude (V peak)', { exact: true }).fill('2');
  await expect(page.getByRole('heading', { name: 'Frequency response', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: 'Run analysis', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Frequency response', exact: true })).toBeVisible();
  expect(timeJobs).toBe(1); expect(frequencyJobs).toBe(2);
});

test('excessive sweep fails actionably and does not break the next run', async ({ page }) => {
  await page.goto('/?mode=build');
  await page.getByLabel('Analysis', { exact: true }).selectOption('ac');
  await page.getByLabel('Points per decade', { exact: true }).fill('1000');
  await page.getByRole('button', { name: 'Run analysis', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('2–1000 frequency points');
  await expect(page.locator('.run-status')).toContainText('Simulation failed');
  await expect(page.getByRole('heading', { name: 'Frequency response', exact: true })).toHaveCount(0);
  await page.getByLabel('Points per decade', { exact: true }).fill('50');
  await page.getByRole('button', { name: 'Run analysis', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Frequency response', exact: true })).toBeVisible();
});

test('undersampled sine playback recommends solving with a smaller interval rather than slowing physics', async ({ page }) => {
  await page.goto('/?mode=build');
  page.once('dialog', dialog => dialog.accept());
  await page.getByLabel('AC example', { exact: true }).selectOption('C');
  await page.getByLabel('Sample interval (ms)', { exact: true }).fill('2');
  await page.getByRole('button', { name: 'Run analysis', exact: true }).click();
  await expect(page.getByText('Sampling warning:', { exact: false })).toContainText('Choose a smaller sample interval');
});
